=== superpck/test-xml/hl7_3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="person">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="nameType"></xs:element>
                <xs:element name="idCard">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[0-9]{13}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="dob" type="xs:date"></xs:element>
                <xs:element name="age">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="0"/>
                            <xs:maxInclusive value="120"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="gender">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="F"/>
                            <xs:enumeration value="M"/>
                            <xs:enumeration value="UN"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="phone" type="phoneType"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="nameType">
        <xs:sequence>
            <xs:element name="preName" type="xs:string"></xs:element>
            <xs:element name="firstName" type="xs:string"></xs:element>
            <xs:element name="middleName" type="xs:string"></xs:element>
            <xs:element name="lastName" type="xs:string"></xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="phoneType">
        <xs:sequence>
            <xs:element name="office" type="phoneNoType"></xs:element>
            <xs:element name="mobile" type="phoneNoType"></xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="phoneNoType">
        <xs:restriction base="xs:string">
            <xs:pattern value="0[0-9]{2}-[0-9]{4}-[0-9]{4}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== superpck/test-xml/hl7_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<person xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="hl7_3.xsd">    
    <name>
        <preName>Mr.</preName>
        <firstName>TestName</firstName>
        <middleName>noname</middleName>
        <lastName>TestLast</lastName>
    </name>
    <idCard>1234567890123</idCard>
    <dob>1900-01-01</dob>
    <age>120</age>
    <gender>M</gender>
    <phone>023-123-1234</phone>
</person>
